- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create nginx group
  group:
    name: nginx
    state: present

- name: Create nginx user
  user:
    name: nginx
    group: nginx
    shell: /sbin/nologin
    home: /var/www
    createhome: false

- name: Ensure Project Folder exists
  ansible.builtin.stat:
    path: "{{ project_folder }}"
  register: frontend_dir_stat

- name: Create Project folder if not existent
  file:
    path: "{{ project_folder }}"
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"
  when: not frontend_dir_stat.stat.exists

- name: Ensure Nginx is running as nginx user
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user nginx;"
  notify: Restart Nginx

- name: Deploy Nginx site configuration - backend
  ansible.builtin.template:
    src: "{{ stack }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ domain }}.conf"
  notify: Restart Nginx

- name: Enable Nginx site
  file:
    src: "{{ nginx_conf_path }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    state: link
  notify: Restart Nginx

- name: Ensure Nginx configuration is valid
  ansible.builtin.shell: nginx -t
  ignore_errors: true
  register: nginx_service_status

- name: Verify Nginx Installation and configuration
  ansible.builtin.include_tasks:
    file: verify.yaml
  when: nginx_service_status.failed
