
- name: Debug - List directory contents
  command: ls -la {{ project_folder }}
  register: dir_contents

- name: Debug - Show directory contents
  debug:
    var: dir_contents.stdout_lines

- name: Display Nginx config status
  ansible.builtin.debug:
    var: nginx_service_status

- name: Fetch Nginx service status
  ansible.builtin.command: systemctl status nginx.service
  register: nginx_status_output
  changed_when: false
  ignore_errors: true

- name: Display Nginx service status details
  ansible.builtin.debug:
    var: nginx_status_output.stdout_lines

- name: Fetch Nginx error log
  ansible.builtin.command: tail -n 20 /var/log/nginx/error.log
  register: nginx_error_log
  changed_when: false
  ignore_errors: true

- name: Display Nginx error log
  ansible.builtin.debug:
    var: nginx_error_log.stdout_lines

- name: Fail the play if Nginx failed to start
  ansible.builtin.fail:
    msg: "Nginx failed to start. Please check the configuration and logs."
  when: nginx_service_status.failed

