---
# tasks file for playbooks/roles/node-exporter

- name: Create directories for Node Exporter
  file:
    path: /opt/node_exporter
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Node Exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz

- name: Unarchive Node Exporter binary
  unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /opt/node_exporter/
    remote_src: true

- name: Set executable permissions for Node Exporter
  file:
    path: /opt/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    state: file
    owner: root
    group: root
    mode: "0755"

- name: Create Node Exporter systemd service
  ansible.builtin.template:
    dest: /etc/systemd/system/node_exporter.service
    src: node_exporter.service.j2
    group: root
    mode: 0664

  notify:
    - Reload systemd
    - Enable and start Node Exporter service

- name: Run Service Check
  import_tasks: service_check.yaml
