- name: Ensure node_exporter is running
  ansible.builtin.systemd:
    name: node_exporter
    state: started
  register: node_exporter_status

- name: Ensure node_exporter is running
  ansible.builtin.systemd:
    name: node_exporter
    state: started
  register: node_exporter_port_status


- name: Check node_exporter endpoint
  ansible.builtin.uri:
    url: "http://localhost:{{ node_exporter_port }}/metrics"
    status_code: 200
  register: node_exporter_http_status

- name: Aggregate service status
  ansible.builtin.debug:
    msg: >
      node_exporter: {{ node_exporter_status }}

- name: Aggregate port check results
  ansible.builtin.debug:
    msg: >
      node_exporter port: {{ node_exporter_port_status }}

- name: Aggregate HTTP endpoint results
  ansible.builtin.debug:
    msg: >
      node_exporter HTTP: {{ node_exporter_http_status }}
