- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Telegraf service
  ansible.builtin.systemd:
    name: telegraf
    state: started
    enabled: yes

- name: Restart Telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
