---
# handlers file for playbooks/roles/node-exporter

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start Node Exporter service
  systemd:
    name: node_exporter
    enabled: true
    state: started
