- name: Set up monitoring tools for monitored machines
  hosts: monitored
  remote_user: "{{ new_username }}"
  become: true
  gather_facts: false

  roles:
    - promtail
    - node-exporter
    - telegraf
