- name: Set up monitoring tools for monitored machines
  hosts: monitor
  remote_user: "{{ new_username }}"
  become: true
  gather_facts: true
  vars_files:
    - "~/private_files/var_files/my_secrets.yml"

  roles:
    - promtail
    - node-exporter
    - telegraf
