---
- name: Create a new user with SSH login using a local SSH key
  hosts: ubuntu_machines
  remote_user: ubuntu
  become: true

  tasks:
    - name: Create a new user
      ansible.builtin.user:
        name: "{{ new_username }}"
        password: "{{ new_user_password }}"
        state: present
        shell: /bin/bash
        create_home: true
        groups: "sudo"
      notify: Reboot the machine

    - name: Create .ssh directory for the new user
      ansible.builtin.file:
        path: /home/{{ new_username }}/.ssh
        state: directory
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: "0700"

    - name: Copy SSH public key to the new user
      ansible.builtin.copy:
        src: "{{ ssh_key_file }}"
        dest: "/home/{{ new_username }}/.ssh/authorized_keys"
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: "0600"

    - name: Disable password authentication for SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Allow the new user to run sudo without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ new_username }}
        create: true
        line: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL"
        validate: "/usr/sbin/visudo -cf %s"

  handlers:
    - name: Reboot the machine
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible playbook"
        reboot_timeout: 10
      notify:
        - Reboot the machine
