- name: Ping and update
  hosts: ubuntu_machines
  remote_user: ubuntu # ec2-user
  become: true
  gather_facts: false

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

  roles:
    - update
    - dependencies

- name: Create new user for all hosts
  ansible.builtin.import_playbook: new_sudo_user.yaml

- name: Import Playbooks for frontend
  ansible.builtin.import_playbook: stack_playbook.yaml

  vars:
    stack: "backend"

- name: Import Playbooks for backend
  ansible.builtin.import_playbook: stack_playbook.yaml

  vars:
    stack: frontend

- name: Import Playbooks for Monitoring
  ansible.builtin.import_playbook: monitors.yaml

- name: Set up monitoring tools for monitored machines
  ansible.builtin.import_playbook: monitored.yaml
