- name: Update all nodes
  hosts: all
  remote_user: ubuntu # ec2-user
  become: true
  become_user: root

  roles:
    - update
    - dependencies

- name: Create new user for all hosts
  ansible.builtin.import_playbook: new_sudo_user.yaml

- name: Import Playbooks for backend and frontend
  ansible.builtin.import_playbook: stack_playbook.yaml

- name: Import Playbooks for monitored machines
  ansible.builtin.import_playbook: monitored.yaml

- name: Import Playbooks for Monitoring
  ansible.builtin.import_playbook: monitors.yaml
