- name: Upload files to {{ stack }}
  remote_user: "{{ new_username }}"
  become: true
  hosts: backend
  roles:
    - copy-folder
    - nginx
    - nodejs
  vars:
    folder_src: "{{ stack }}/"
    stack: backend

- name: Upload files to {{ stack }}
  remote_user: "{{ new_username }}"
  become: true
  hosts: frontend
  roles:
    - copy-folder
    - nginx
    - nodejs
  vars:
    folder_src: "{{ stack }}/"
    stack: frontend
