- name: "Deploy App to {{ stack }}"
  remote_user: "{{ new_username }}"
  become: true
  hosts: "{{ stack }}"
  vars_files:
    - "~/private_files/var_files/my_secrets.yml"
  vars:
    pm2_name: "glorious"

  roles:
    - github_clone
    - nginx
    - nodejs

  # vars:
  # allowed_ports:
  #   - { port: 80, proto: tcp }
  #   - { port: 443, proto: tcp }
  #   - { port: "{{ ansible_port }}", proto: tcp }
  #   - { port: "{{ pm2_port }}", proto: tcp }
  #   - { port: "{{ promtail_port }}", proto: tcp }
  #   - { port: "{{ prometheus_port }}", proto: tcp }
  #   - { port: "{{ telegraf_port }}", proto: tcp }
  #   - { port: "{{ loki_port }}", proto: tcp }
  #   - { port: "{{ grafana_port }}", proto: tcp }
  #   - { port: "{{ node_exporter_port }}", proto: tcp }
