- name: Upload files to {{ stack }}
  hosts: { { stack } }
  remote_user: ubuntu
  become: true
  become_user: "{{ new_username }}"

  roles:
    - nginx
    - copy-folder
    - nodejs

  vars:
    folder_src: "{{ stack }}/"
