---

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set UFW default policy to deny all incoming traffic
  ansible.builtin.ufw:
    state: enabled
    policy: deny

- name: Block specific ports
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ allowed_ports }}"
