---
# tasks file for roles/grafana
- name: Create directories for Grafana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  loop:
    - /opt/grafana
    - /opt/grafana/conf
    - /opt/grafana/provisioning
    - /opt/grafana/provisioning/datasources
    - /opt/grafana/provisioning/dashboards

- name: Download Grafana binary
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: /tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz

- name: Unarchive Grafana binary
  ansible.builtin.unarchive:
    src: /tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz
    dest: /opt/grafana/
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Set executable permissions for Grafana
  ansible.builtin.file:
    path: /opt/grafana/bin/grafana-server
    state: file
    owner: root
    group: root
    mode: "0755"

- name: Create Grafana configuration file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/conf/custom.ini
    owner: root
    group: root
    mode: "0644"

- name: Create Prometheus datasource configuration
  ansible.builtin.template:
    src: prometheus_datasource.yml.j2
    dest: /opt/grafana/provisioning/datasources/prometheus.yml
    owner: root
    group: root
    mode: "0644"

- name: Create Loki datasource configuration
  ansible.builtin.template:
    src: loki_datasource.yml.j2
    dest: /opt/grafana/provisioning/datasources/loki.yml
    owner: root
    group: root
    mode: "0644"

- name: Create Grafana systemd service
  ansible.builtin.template:
    dest: /etc/systemd/system/grafana.service
    src: grafana.service.j2
    group: root
    mode: "0664"
  notify:
    - Reload systemd
    - Enable and start Grafana service

# - name: flush handlers
#   ansible.builtin.meta: flush_handlers

# - name: Verify Installation and Configuration
#   import_tasks: service_check.yaml

- name: Remove Grafana tarball
  ansible.builtin.file:
    path: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    state: absent
