---
# tasks file for playbooks/roles/grafana

- name: Create directories for Grafana
  file:
    path: /opt/grafana
    state: directory
    owner: root
    group: root
    mode: '0755'
   

- name: Download Grafana binary
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: /tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz

- name: Unarchive Grafana binary
  unarchive:
    src: /tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz
    dest: /opt/grafana/
    remote_src: yes

- name: Set executable permissions for Grafana
  file:
    path: /opt/grafana/bin/grafana-server
    state: file
    owner: root
    group: root
    mode: '0755'



- name: Create Grafana systemd service
  ansible.builtin.template: 
    dest: /etc/systemd/system/grafana.service
    src: grafana.service.j2
    group: root
    mode: 0664

  notify: 
    - Reload systemd
    - Enable and start Grafana service


