---
# tasks file for roles/grafana
- name: Create directories for Grafana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  loop:
    - /opt/grafana
    - /opt/grafana/conf

- name: Download Grafana binary
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: /tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz

- name: Unarchive Grafana binary
  ansible.builtin.unarchive:
    src: /tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz
    dest: /opt/grafana/
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Set executable permissions for Grafana
  ansible.builtin.file:
    path: /opt/grafana/bin/grafana-server
    state: file
    owner: root
    group: root
    mode: "0755"

- name: Create Grafana systemd service
  ansible.builtin.template:
    dest: /etc/systemd/system/grafana.service
    src: grafana.service.j2
    group: root
    mode: "0664"
  notify:
    - Reload systemd
    - Enable and start Grafana service

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: Run Service Check
  import_tasks: service_check.yaml

- name: Remove Prometheus tarball
  ansible.builtin.file:
    path: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    state: absent
