
- name: Check Grafana endpoint
  ansible.builtin.uri:
    url: "http://localhost:{{ grafana_port }}/api/health"
    status_code: 200
  register: grafana_http_status

- name: Ensure Grafana is running
  ansible.builtin.systemd:
    name: grafana
    state: started
  register: grafana_status

- name: "Verify grafana is listening on port {{ grafana_port }}"
  wait_for:
    port: "{{ grafana_port }}"
    timeout: 30



- name: Aggregate service status
  debug:
    msg: >
      Grafana: {{ grafana_status }}


- name: Aggregate HTTP endpoint results
  debug:
    msg: >
      Grafana HTTP: {{ grafana_http_status }}