---
- name: Validate required variables
  ansible.builtin.fail:
    msg: "Required variables not set: ssh_key_file, new_user_password, DB_PASSWORD, github_token"
  when:
    - ssh_key_file is not defined
    - new_user_password is not defined
    - DB_PASSWORD is not defined
    - github_token is not defined

- name: Create a new user
  ansible.builtin.user:
    name: "{{ new_username }}"
    password: "{{ new_user_password }}"
    state: present
    shell: /bin/bash
    create_home: true
    groups: "sudo"
  notify: Reboot the machine

- name: Create .ssh directory for the new user
  ansible.builtin.file:
    path: /home/{{ new_username }}/.ssh
    state: directory
    owner: "{{ new_username }}"
    group: "{{ new_username }}"
    mode: "0700"

- name: Copy SSH public key to the new user
  ansible.builtin.copy:
    src: "{{ ssh_key_file }}"
    dest: "/home/{{ new_username }}/.ssh/authorized_keys"
    owner: "{{ new_username }}"
    group: "{{ new_username }}"
    mode: "0600"
    remote_src: false

- name: Disable password authentication for SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: Allow the new user to run sudo without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ new_username }}
    create: true
    line: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
