- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
