- name: Upload files to backend
  hosts: library
  remote_user: ubuntu # ec2-user
  become: true
  become_user: root

  roles:
    - nginx
    - nodejs
    - copy-folder
  vars:
    folder_src: "{{ stack }}/"
