---
# handlers file for playbooks/roles/prometheus
- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
    daemon_reload: true
