
- name: Configure Nginx-{{ stack }} 
  ansible.builtin.template:
    src: ./files/{{ stack }}_nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0555"
  notify: Restart nginx

- name: Configure Domain
  ansible.builtin.template: dest=/etc/nginx/sites-available/{{ domain }}.conf
            src=sites-available/proxy.conf.j2
            owner=root
            group=root
            mode=0664

- name: Configure Html Domain
  ansible.builtin.template: dest=/etc/nginx/sites-available/{{ domain }}.conf
            src=sites-available/html.conf.j2
            owner=root
            group=root
            mode=0664

- name: Configure Frontend Domain
  ansible.builtin.template: dest=/etc/nginx/sites-available/{{domain}}.conf
            src=sites-available/frontend.conf.j2
            owner=root
            group=root
            mode=0664

- name: Enable nginx site
  file: src=/etc/nginx/sites-available/{{domain}}.conf
        dest=/etc/nginx/sites-enabled/{{domain}}.conf
        state=link
        