- name: Ensure frontend directory exists
  ansible.builtin.stat:
    path: "{{ source_folder }}"
  register: frontend_dir_stat

- name: Abort if frontend directory does not exist
  ansible.builtin.fail:
    msg: "The frontend directory does not exist."
  when: not frontend_dir_stat.stat.exists

- name: Copy frontend environment variables
  ansible.builtin.template:
    src: frontend.env.j2
    dest: "{{ source_folder }}/.env"
  when: frontend_dir_stat.stat.exists
  changed_when: false

- name: Delete NPM Folder if already existent
  file:
    path: "{{ source_folder }}/node_modules"
    state: absent

- name: Install frontend packages based on package.json
  community.general.npm:
    path: "{{ source_folder }}"

- name: Build the React app if build folder is missing
  ansible.builtin.command:
    cmd: npm run build
    chdir: "{{ source_folder }}"
  args:
    creates: "{{ source_folder }}/build/index.html"

- name: Create Project Folder
  file:
    path: "{{ project_folder }}"
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"

- name: Copy Build Files
  copy:
    src: "{{ source_folder }}/build/"
    dest: "{{ project_folder }}"
    owner: nginx
    group: nginx
    mode: "0755"
    remote_src: true

- name: Set correct ownership and permissions for project folder
  file:
    path: "{{ project_folder }}"
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"
    recurse: yes
