---
# tasks file for nodejs-latest

- name: Add NodeSource repository for Node.js version {{ node_version }}
  ansible.legacy.shell: "curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash -"

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Validate required variables
  fail:
    msg: "Required variables not set"
  when:
    - DB_USERNAME is not defined
    - DB_PASSWORD is not defined
    - backend_port is not defined
    - frontend_port is not defined
    - admin_Mail is not defined
    - mail_Password is not defined

- name: "Run deployment tasks for {{ stack }}"
  import_tasks: "deploy-{{ stack }}.yml"
# - name: "Verify PM2 Installation and configuration for backend"
#   ansible.builtin.include_tasks:
#     file: verify.yaml
#   when: stack == "backend"
